[package]
name = "rover-rtc"
version = "0.1.0"
edition = "2021"

[dependencies]
str0m = "0.11.0"
tracing = "0.1.37"
rouille = { version = "3.6.2", features = ["ssl"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "std"] }
systemstat = "0.2.2"
serde_json = "1.0.145"
